name: Continuous Deployment
on:
  push:
    branches: [ master ]
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2      
      - name: Setup Python
        uses: actions/setup-python@v2.1.4
        with:
          python-version: 3.8
          architecture: x64
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Build Site
        run: python -m callystio build
      - name: Upload Artifact
        uses: actions/upload-artifact@v2.2.3
        with:
          path: dist
          name: artifact

  deploy:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2.0.9
      - name: Simple GitHub Pages Deploy Action
        uses: rdarida/simple-github-pages-deploy-action@v1
        with:
          git-base-folder: dist
          commit-message: Auto build static site